### ISSUE TITLE
Export build command to Makefile

### ISSUE THREAD

**Issue by StuckiSimon** [Goldinteractive/Sackmesser#2]
Currently there is a `make build` command - but it is only in `Makefile.local`.

https://github.com/Goldinteractive/Sackmesser/blob/999042da4d11901a22d8e0e2a21a57624d2acbe3/Makefile.local#L35

Is there a reason why it's not exported using the public `Makefile`?

**Comment by christianruhstaller** [comment]
It isn't considered to use it in a public facing way. That's why it was not implemented. But other than that there is no reason.
